# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "ru"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
# plugins:
  # Automatically fetch Medium follower count
#   - MediumFollowersCountPlugin:
#       username: zhgchgli
  # Automatically fetch Github repo star count
#   - GithubRepoStarsCountPlugin:
#       - ZhgChgLi/ZMarkupParser
#       - ZhgChgLi/ZReviewTender
#       - ZhgChgLi/ZMediumToMarkdown
#       - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "ThatMaidGuy - –±–ª–æ–≥–≥–µ—Ä-—Ä–∞–∑—Ä–∞–±–æ—Ç—á–∏–∫"

# Avatar image path
avatar: "./images/logo.jpg"

# Name section text
name: "ThatMaidGuy"

# Tagline section text
tagline: >-
    <p><b>–¢–æ—Ç —Å–∞–º—ã–π –ø–∞—Ä–µ–Ω—å-–≥–æ—Ä–Ω–∏—á–Ω–∞—è.</b></p>
    <br>
    <p>–ü—Ä–æ–≥—Ä–∞–º–º–∏—Å—Ç, backend-—Ä–∞–∑—Ä–∞–±–æ—Ç—á–∏–∫, –≥–µ–π–º–¥–µ–≤, –±–ª–æ–≥–µ—Ä, –º–æ–Ω—Ç–∞–∂–µ—Ä, —Å—Ü–µ–Ω–∞—Ä–∏—Å—Ç –∏ —ç–Ω—Ç—É–∑–∏–∞—Å—Ç</p>
    <p>–†–∞–±–æ—Ç–∞—é –Ω–∞–¥ <b>Ada's Maidness</b></p>

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
otherlinks:
    - link:
        icon: "fa-brands fa-internet-explorer"
        text: "–ú–æ–π –ø–æ–ª–Ω–æ—Ü–µ–Ω–Ω—ã–π —Å–∞–π—Ç (–∏–∑ 2007üòâ)"
        url: "https://thatmaidguy.su"
        alt: "IE6"
        title: "IE6"
        target: "_blank"

links:
  - link:
      icon: "icon-boosty"
      text: "–ö—É–ø–∏—Ç—å –ø–æ–¥–ø–∏—Å–∫—É –Ω–∞ Boosty"
      url: "https://boosty.to/thatmaidguy"
      alt: "Boosty"
      title: "Boosty"
      target: "_blank"
  - link:
      icon: "icon-donationalerts"
      text: "–î–∞—Ç—å –¥–µ–Ω—å–≥—É —á–µ—Ä–µ–∑ DonationAlerts"
      url: "https://www.donationalerts.com/r/thatmaidguy"
      alt: "DonationAlerts"
      title: "DonationAlerts"
      target: "_blank"

games:
  - link:
      icon: "fa-brands fa-itch-io"
      text: "–ò–≥—Ä—ã –Ω–∞ Itch.IO"
      url: "https://thatmaidguy.itch.io/"
      alt: "Itch.IO"
      title: "Itch.IO"
      target: "_blank"
  - link:
      icon: "icon-gamejolt"
      text: "–ò–≥—Ä—ã –Ω–∞ GameJolt"
      url: "https://gamejolt.com/invite/ThatMaidGuy"
      alt: "GameJolt"
      title: "GameJolt"
      target: "_blank"
  - link:
      icon: "fa-solid fa-globe"
      text: "–°—Ç–∞—Ä—ã–π –∞—Ä—Ö–∏–≤ —Å–æ —Å—Ç–∞—Ä—ã–º–∏ –∏–≥—Ä–∞–º–∏"
      url: "https://thatmaidguy.github.io/old-archive"
      alt: "–°—Ç–∞—Ä—ã–π –∞—Ä—Ö–∏–≤"
      title: "–°—Ç–∞—Ä—ã–π –∞—Ä—Ö–∏–≤"
      target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-youtube"
      url: "https://youtube.com/@thatmaidguy"
      title: "YouTube –∫–∞–Ω–∞–ª"
      alt: "YouTube –∫–∞–Ω–∞–ª"
      target: "_blank"
  - social:
      icon: "fa-brands fa-telegram"
      url: "https://t.me/ThatMaidGuyChan"
      title: "Telegram –∫–∞–Ω–∞–ª"
      alt: "Telegram –∫–∞–Ω–∞–ª"
      target: "_blank"
  - social:
      icon: "fa-brands fa-twitch"
      url: "https://www.twitch.tv/thatmaidguy"
      title: "Twitch"
      alt: "Twitch"
      target: "_blank"
  - social:
      icon: "fa-brands fa-tiktok"
      url: "https://tiktok.com/@thatmaidguy"
      title: "TikTok"
      alt: "TikTok"
      target: "_blank"
  - social:
      icon: "fa-brands fa-discord"
      url: "https://discord.gg/gm8SXU8yMm"
      title: "Discord"
      alt: "Discord"
      target: "_blank"
  - social:
      icon: "fa-brands fa-github"
      url: "https://github.com/WheatleyHDD"
      title: "GitHub"
      alt: "GitHub"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:thatmaidguy@ya.ru"
      title: "Email: thatmaidguy@ya.ru"
      alt: "me@thatmaidguy.ru"
      target: "_blank"

# Footer text
footer: >
    –ö—É, –ø–æ–¥–ø–∏—à–∏—Å—å —Ä–∞–¥–∏ –≥–æ—Ä–Ω–∏—á–Ω—ã—Ö :3

# Footer copyright message
# Linkyee is a 100% free, open-source project‚Äîfeel free to modify the copyright message as you like. :)
copyright: >
  ¬© 2024-2025  <a href="https://thatmaidguy.ru" target="_blank">ThatMaidGuy</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
